server:
  port: 8080

spring:
  application:
    name: master-annonce
  datasource:
    url: jdbc:postgresql://localhost:5432/master_annonce
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.univ_paris8.iut.montreuil: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
