MasterAnnonceLogin {
    org.univ_paris8.iut.montreuil.dev_avance.security.DbLoginModule required;
};

MasterAnnonceToken {
    org.univ_paris8.iut.montreuil.dev_avance.security.TokenLoginModule required;
};
